app/project/forms.py
"""Implements forms used in the projects ui."""

from flask_wtf import (
    Form,
)
from wtforms import (
    HiddenField,
    PasswordField,
    StringField,
    SubmitField,
)
from wtforms.validators import (
    Required, EqualTo
)


class NewProjectForm(Form):
    name = StringField('Name', validators=[Required()])
    submit = SubmitField('Create')


class EditProjectForm(Form):
    name = StringField('Name', validators=[Required()])
    submit = SubmitField('Save Changes')


class APIKeyForm(Form):
    key = HiddenField()
    name = StringField('Name', validators=[Required()])
    submit = SubmitField('Save')


class NewPlatformProxyForm(Form):
    username = StringField('Username', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])
    confirm_password = PasswordField('Confirm password', validators=[
        Required(),
        EqualTo('password')
    ])
    submit = SubmitField('Create')

app/project/__init__.py
"""Implements the project ui."""

from flask import Blueprint

project = Blueprint('project', __name__)

from . import (
    forms,
    views,
    )

__all__ = ['project']

app/project/views.py
"""Implements project endpoints."""

from datetime import datetime
import random
import re

from flask import (
    current_app, flash, redirect, render_template,
    request,
)
from flask_breadcrumbs import register_breadcrumb
from flask_login import (
    current_user, login_required,
)
import paramiko

from . import project
from .forms import (
    APIKeyForm, EditProjectForm, NewPlatformProxyForm, NewProjectForm,
)
from app import (
    cache, db, ec2client, ec2resource, sshclient
)
from app.confirm import confirm_required
from app.utils.constructors import (
    edit_project, view_project, project_add_api_key,
)
from app.utils.decorators import (
    confirmed_required,
)
from app.utils.platform_wrapper import AgentPlatformWrapper
from app.utils.models import (
    APIKey, Platform, PlatformProxy, Project,
)
from flask.helpers import url_for


@project.route('/')
@login_required
@confirmed_required
@register_breadcrumb(project, 'breadcrumbs.project', 'Projects')
def index():
    """Render index page for the project context."""
    projects = Project.query.filter_by(owner_id=current_user.id).all()
    page_vars = {
        'sidebar_class': ' no-sidebars',
        'navwell': True,
        'title': 'Manage Your Projects',
        'page_header': 'Projects',
        'projects': projects
    }
    return render_template('project/index.html', vars=page_vars)


@project.route('/add', methods=['GET', 'POST'])
@login_required
@confirmed_required
@register_breadcrumb(project, 'breadcrumbs.project.add', 'New Project')
def add():
    """Present form to add a project"""
    form = NewProjectForm()

    if form.validate_on_submit():
        p = Project(
            name=form.name.data,
            owner_id=current_user.id,
            created=datetime.now()
        )
        db.session.add(p)
        db.session.commit()
        return redirect(url_for('project.view', pid=p.id))

    page_vars = {
        'sidebar_class': ' no-sidebars',
        'navwell': True,
        'title': 'Create a New Project',
        'page_header': 'New Project',
        'form': form
    }
    return render_template('project/add.html', vars=page_vars)


@project.route('/<int:pid>')
@login_required
@confirmed_required
@register_breadcrumb(project, 'breadcrumbs.project.view', '', dynamic_list_constructor=view_project)
def view(pid):
    """View a project."""
    p = Project.query.filter_by(id=pid).first()
    if p is None or (current_user.id != p.owner_id):
        return render_template('error/404.html', vars={}), 404

    instance = None
    agents = None
    jade_up = False
    platform = p.platform.first()
    if platform is None:
        pass
    else:
        instance = ec2resource.Instance(platform.instance_id)
        apw = AgentPlatformWrapper(instance.public_ip_address)
        if apw.is_up():
            jade_up = True
            agents = apw.api_agents()

    proxy_instance = None
    proxy = p.proxy.first()
    if proxy is not None:
        proxy_instance = ec2resource.Instance(proxy.instance_id)

    keys = p.api_keys.all()

    page_vars = {
        'sidebar_class': ' sidebar' if platform is not None else ' no-sidebars',
        'sidebar_right': True if platform is not None else False,
        'navwell': True,
        'title': p.name,
        'page_header': p.name,
        'project_title': p.name,
        'pid': p.id,
        'platform': True if platform is not None else False,
        'instance': instance,
        'proxy': True if proxy is not None else False,
        'proxy_instance': proxy_instance,
        'api_keys': keys,
        'agents': agents,
        'jade_up': 'Up' if jade_up else 'Down'
    }
    return render_template('project/view.html', vars=page_vars)


@project.route('/<int:pid>/edit', methods=['GET', 'POST'])
@login_required
@confirmed_required
@register_breadcrumb(project, 'breadcrumbs.project.edit', '', dynamic_list_constructor=edit_project)
def edit(pid):
    """Edit a project."""
    p = Project.query.filter_by(id=pid).first()
    if p is None or (current_user.id != p.owner_id):
        return render_template('error/404.html', vars={}), 404

    form = EditProjectForm()
    if form.validate_on_submit():
        temp = p.name
        p.name = form.name.data

        db.session.add(p)
        db.session.commit()

        flash('Project "{0}" has been updated.'
              .format(temp), 'success')
        return redirect(url_for('project.view', pid=p.id))

    form.name.data = p.name
    page_vars = {
        'sidebar_class': ' no-sidebars',
        'navwell': True,
        'title': p.name,
        'page_header': 'Edit ' + p.name,
        'pid': p.id,
        'form': form
    }
    return render_template('project/edit.html', vars=page_vars)


@project.route('/<int:pid>/delete')
@login_required
@confirmed_required
@confirm_required(
    'Are you sure you want to delete this project?',
    'I am sure', 'project.view', ['pid'], 'danger'
)
def delete(pid):
    """Delete a project."""
    p = Project.query.filter_by(id=pid).first()
    if p is None or (current_user.id != p.owner_id):
        return render_template('error/404.html', vars={}), 404

    plt = p.platform.first()
    if plt is not None:
        instance = ec2resource.Instance(plt.instance_id)
        ec2client.disassociate_address(AssociationId=plt.eip_assoc_id)
        ec2client.release_address(AllocationId=plt.eip_alloc_id)
        instance.terminate()
        db.session.delete(plt)

    proxy = p.proxy.first()
    if proxy is not None:
        proxy_instance = ec2resource.Instance(proxy.instance_id)
        ec2client.disassociate_address(AssociationId=proxy.eip_assoc_id)
        ec2client.release_address(AllocationId=proxy.eip_alloc_id)
        proxy_instance.terminate()
        db.session.delete(proxy)

    keys = p.api_keys.all()
    for key in keys:
        db.session.delete(key)

    db.session.delete(p)
    db.session.commit()

    flash('Project "{0}" has been deleted.'
          .format(p.name), 'success')
    return redirect(url_for('project.index'))


@project.route('/<int:pid>/platform/add')
@login_required
@confirmed_required
@confirm_required(
    'Are you sure you want to add a new platform to this project?',
    'I am sure', 'project.view', ['pid'], 'warning'
)
def add_platform(pid):

    p = Project.query.filter_by(id=pid).first()

    vpc = list(ec2resource.vpcs.filter(Filters=[{
        'Name': 'tag:Name',
        'Values': [current_app.config['AWS_JADEVPC_NAME']]
    }]))[0]

    subnet = random.choice(
        list(filter(lambda x: x.available_ip_address_count > 0, list(
            ec2resource.subnets.filter(Filters=[{
                'Name': 'vpc-id',
                'Values': [vpc.vpc_id]
            }])
        )))
    )

    image = list(ec2resource.images.filter(Filters=[{
        'Name': 'tag:Name',
        'Values': ['jade-platform-{0}'.format(current_app.config['AWS_JADEPLATFORM_VERSION'])]
    }]))[0]

    security_group = list(ec2resource.security_groups.filter(Filters=[{
        'Name': 'group-name',
        'Values': [current_app.config['AWS_JADEVPC_SECURITYGROUP']]
    }]))[0]

    instances = ec2resource.create_instances(
        ImageId=image.image_id,
        MinCount=1,
        MaxCount=1,
        KeyName=current_app.config['AWS_JADEVPC_KEYNAME'],
        SecurityGroupIds=[
            security_group.group_id
        ],
        UserData=render_template('project/aws-platform-userdata.txt'),
        InstanceType='t2.small',
        SubnetId=subnet.subnet_id
    )

    if len(instances) > 0:
        instance = instances[0]
        instance.wait_until_running()
        instance.load()
        eip = ec2client.allocate_address(Domain='vpc')
        aid = ec2client.associate_address(
            AllocationId=eip['AllocationId'],
            InstanceId=instance.instance_id,
            PrivateIpAddress=instance.private_ip_address
        )

        instance.create_tags(
            Tags=[
                {
                    'Key': 'Name',
                    'Value': 'jade-{0}-{1}'.format(p.owner.username, p.name)
                }
            ]
        )

        platform = Platform(
            secret=Platform.generate_secret(),
            project_id=pid,
            instance_id=instance.instance_id,
            ip_address=eip['PublicIp'],
            eip_alloc_id=eip['AllocationId'],
            eip_assoc_id=aid['AssociationId']
        )
        db.session.add(platform)
        db.session.commit()
        flash('Agent platform created.', 'success')
    else:
        flash('The Agent Platform could not be created.', 'danger')
    return redirect(url_for('project.view', pid=pid))


@project.route('<int:pid>/platform/logs')
@login_required
@confirmed_required
@register_breadcrumb(project, 'breadcrumbs.project.view.logs', 'Logs')
def platform_logs(pid):
    """Display last 300 lines of each platform process' log."""
    p = Project.query.filter_by(id=pid).first()
    plt = p.platform.first()

    pkey = paramiko.RSAKey.from_private_key_file(
        current_app.config['LOCAL_JADEVPC_KEY'])
    sshclient.connect(
        hostname=plt.ip_address,
        username=current_app.config['JADEVPC_USER'],
        pkey=pkey
    )

    main_log = sshclient.exec_command(
        'journalctl -u jadeplatform-main.service -n 300 --system')[1].read().decode('utf-8')
    main_log = re.sub('\n.+\ssystemd.+', '', main_log)
    main_log = re.sub('\n.+\ssudo.+', '', main_log)
    main_log = re.sub(
        'ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+ bash\[[0-9]+\]', '', main_log)

    backup_log = sshclient.exec_command(
        'journalctl -u jadeplatform-backup.service -n 300')[1].read().decode('utf-8')
    backup_log = re.sub('\n.+\ssystemd.+', '', backup_log)
    backup_log = re.sub('\n.+\ssudo.+', '', backup_log)
    backup_log = re.sub(
        'ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+ bash\[[0-9]+\]', '', backup_log)

    backup2_log = sshclient.exec_command(
        'journalctl -u jadeplatform-backup-2.service -n 300')[1].read().decode('utf-8')

app/templates/project/add-api-key.html
{% extends "base.html" %}


{% block page_content %}
{{ super() }}
<p>Your generated API key is:</p>
<p>{{ vars['key'] }}</p>
<p>Please make note of this key before clicking save. It will not be shown to
    you again.</p>
<form method="post" class="form" role="form">
    {{ vars['form'].hidden_tag() }}
    <div class="form-group{% if vars['form'].name.errors %} has-error{% endif %}">
        {{ vars['form'].name.label(class_='control-label') }}
        {{ vars['form'].name(class_='form-control', maxlength=32) }}
        {% for message in vars['form'].name.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    <a role="button" class="btn btn-default"
        href="{{ url_for('project.view', pid=vars['pid'])}}">
        Cancel
    </a>
    {{ vars['form'].submit(class_='btn btn-default') }}
</form>
{% endblock page_content %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/project/add.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}

<div id="new-project-form-container">
	<form method="post" class="form" role="form">
		{{ vars['form'].hidden_tag() }}
		
		<div class="form-group{% if vars['form'].name.errors %} has-error{% endif %}">
			{{ vars['form'].name.label(class_='control-label') }}
            {{ vars['form'].name(class_='form-control') }}
            {% for message in vars['form'].name.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
		</div>
		
		<a role="button" class="btn btn-default"
			href="{{ url_for('project.index')}}">
			Cancel
		</a>
		{{ vars['form'].submit(class_='btn btn-default') }}
	</form>
</div>
{% endblock %}

app/templates/project/edit.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}

<div id="edit-project-form-container">
	<form method="post" class="form" role="form">
		{{ vars['form'].hidden_tag() }}
		
		<div class="form-group{% if vars['form'].name.errors %} has-error{% endif %}">
			{{ vars['form'].name.label(class_='control-label') }}
            {{ vars['form'].name(class_='form-control') }}
            {% for message in vars['form'].name.errors %}
            <p class="help-block">{{ message }}</p>
            {% endfor %}
		</div>
		<a role="button" class="btn btn-default"
			href="{{ url_for('project.view', pid=vars['pid'])}}">
			Cancel
		</a>
		{{ vars['form'].submit(class_='btn btn-default') }}
	</form>
</div>
{% endblock %}

app/templates/project/index.html
{% extends "base.html" %}

{% block body_class %}{{ super() }}{% endblock %}

{% block page_actions %}
{{ super() }}
<a role="button" class="btn btn-default"
	href="{{ url_for('project.add')}}">
	Create Project
</a>
{% endblock %}

{% block page_content %}
{{ super() }}

<div id="projects-container">
	<table id="projects-table" class="table table-compact table-striped">
    	<thead>
    	    <tr>
    	        <th>Name</th>
    	        <th>Actions</th>
    	    </tr>
    	</thead>
    	<tbody>
            {% for project in vars['projects']: %}
    	    <tr>
    	        <td class="project-name">{{ project.name }}</td>
    	        <td class="project-actions">
    	            <a href="{{ url_for('project.view', pid=project.id) }}">View</a>
                    <a href="{{ url_for('project.edit', pid=project.id) }}">Edit</a>
    	        </td>
    	    </tr>
            {% endfor %}
    	</tbody>
	</table>
</div>
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/project/logs.html
{% extends "base.html" %}

{% block page_actions %}
{{ super() }}
{% endblock %}

{% block page_content %}
{{ super() }}
<div class="panel panel-default">
    <div class="panel-heading">Main Container</div>
    <div class="panel-body">
        <textarea class="form-control" rows="20">{{ vars['main_log'] }}</textarea>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">Backup to Main Container</div>
    <div class="panel-body">
        <textarea class="form-control" rows="20">{{ vars['backup_log'] }}</textarea>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">Second Backup to Main Container</div>
    <div class="panel-body">
        <textarea class="form-control" rows="20">{{ vars['backup2_log'] }}</textarea>
    </div>
</div>


<div class="panel panel-default">
    <div class="panel-heading">Service Container</div>
    <div class="panel-body">
        <textarea class="form-control" rows="20">{{ vars['container_log'] }}</textarea>
    </div>
</div>
{% endblock %}

app/templates/project/new-proxy.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
<form class="form col-md-6" role="form" method="post">
    {{ vars['form'].hidden_tag() }}
        
    <div class="form-group{% if vars['form'].username.errors %} has-error{% endif %}">
        {{ vars['form'].username.label(class_='control-label') }}
        {{ vars['form'].username(class_='form-control') }}
        {% for message in vars['form'].username.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
        
    <div class="form-group{% if vars['form'].password.errors %} has-error{% endif %}">
        {{ vars['form'].password.label(class_='control-label') }}
        {{ vars['form'].password(class_='form-control') }}
        {% for message in vars['form'].password.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
        
    <div class="form-group{% if vars['form'].confirm_password.errors %} has-error{% endif %}">
        {{ vars['form'].confirm_password.label(class_='control-label') }}
        {{ vars['form'].confirm_password(class_='form-control') }}
        {% for message in vars['form'].confirm_password.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>

    {{ vars['form'].submit(class_='btn btn-default') }}
</form>
{% endblock %}

app/templates/project/view.html
{% extends "base.html" %}

{% block page_actions %}
{{ super() }}

{% if not vars['platform']: %}
<a role="button" class="btn btn-default"
    href="{{ url_for('project.add_platform', pid=vars['pid']) }}">
    Add Platform
</a>
{% endif %}

{% if not vars['proxy']: %}
<a role="button" class="btn btn-default"
    href="{{ url_for('project.add_platform_proxy', pid=vars['pid']) }}">
    Add Proxy
</a>
{% endif %}

<!--<a role="button" class="btn btn-default"
    href="{{ url_for('project.add_api_key', pid=vars['pid']) }}">
    Add API Key
</a>-->

<a role="button" class="btn btn-default"
	href="{{ url_for('project.edit', pid=vars['pid']) }}">
	Edit
</a>


<a role="button" class="btn btn-danger"
    href="{{ url_for('project.delete', pid=vars['pid']) }}">
    Delete
</a>

{% endblock %}

{% block page_content %}
{{ super() }}

{% if vars['platform']: %}
<div class="platform panel panel-default" id="platform-{{ pid }}">
	<div class="panel-heading">
        Platform Info
        {% if vars['jade_up'] == 'Up': %}
        <div class="dropdown platform-options-dropdown pull-right">
            <a class="dropdown-toggle" role="button"
                    id="platform-options-dropdown" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-cog"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="platform-options-dropdown">
                <li>
                    <a href="{{ url_for('project.platform_logs', pid=vars['pid']) }}">
                        View logs
                    </a>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                    <a href="{{ url_for('project.delete_platform', pid=vars['pid']) }}">Delete</a>
                </li>
            </ul>
        </div>
        {% endif %}
    </div>
	<div class="panel-body">
		<span>IP Address: {{ vars['instance'].public_ip_address }}</span><br>
		<span>VPS State: {{ vars['instance'].state['Name'] }}</span><br>
        <span>JADE Platform: {{ vars['jade_up'] }}</span>
	</div>
</div>
{% endif %}



{% if vars['proxy']: %}
<div class="panel panel-default">
    <div class="panel-heading">
        Proxy Info
        <div class="dropdown proxy-options-dropdown pull-right">
            <a class="dropdown-toggle" role="button"
                    id="proxy-options-dropdown" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <span class="glyphicon glyphicon-cog"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="proxy-options-dropdown">
                <li role="separator" class="divider"></li>
                <li>
                    <a href="{{ url_for('project.delete_platform_proxy', pid=vars['pid']) }}">Delete</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="panel-body">
        <span>IP Address: {{ vars['proxy_instance'].public_ip_address }}</span><br>
        <span>Proxy State: {{ vars['proxy_instance'].state['Name'] }}</span><br>
    </div>
</div>
{% endif %}

{% if vars['api_keys']: %}
<div class="platform panel panel-default" id="platform-{{ pid }}-keys">
    <div class="panel-heading">API Keys</div>
    <div class="panel-body">
        <table class="table table-compact table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Key</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for key in vars['api_keys'] %}
                <tr>
                    <td>{{ key.name }}</td>
                    <td>{{ ''.join([key.key[:10], '...']) }}</td>
                    <td>
                        <a role="button" class="btn btn-danger"
                            href="{{ url_for('project.delete_api_key', pid=vars['pid'], kid=key.id) }}">
                            Delete
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

{% block sidebar_right %}
<div class="panel panel-default">
	<div class="panel-heading">Agents</div>
	<div class="panel-body">
		{% for agent in vars['agents']['agents']: %}
		<span class="platform-agent">{{ agent['Name'] }}</span>
		{% endfor %}
	</div>
</div>
{% endblock %}