app/main/forms.py
"""Implements forms used in the main Blueprint ui."""

from flask_wtf import Form

from wtforms import (
    BooleanField,
    StringField,
    SubmitField,
    TextAreaField,
)
from wtforms.fields.html5 import (
    EmailField,
)
from wtforms.validators import (
    Required,
)


class ContactForm(Form):
    name = StringField('name', validators=[Required()])
    email = EmailField('email', validators=[Required()])
    msg = TextAreaField('message', validators=[Required()])
    cc = BooleanField('cc myself')
    submit = SubmitField('Send')

app/main/__init__.py
"""Implements the main ui."""

from flask import Blueprint

main = Blueprint('main', __name__)

from . import (
    errors,
    views,
    )
from ..utils.models import Permission

__all__ = ['main']


@main.app_context_processor
def inject_permissions():
    """Make permissions available in all template files."""
    return dict(Permission=Permission)

app/main/views.py
"""Implements main endpoints."""

from flask import (
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_breadcrumbs import register_breadcrumb

from app.main import main
from app.main.forms import ContactForm
from app.utils.mail import send_mail


@main.route('/')
@register_breadcrumb(main, 'breadcrumbs.', 'Home')
def index():
    """Render index page."""
    page_vars = {
        'jumbotron': True,
        'title': 'Welcome to PhaseMetrics'
    }
    return render_template('main/index.html', vars=page_vars)


@main.route('/products')
def products():
    """Render Products page."""
    page_vars = {
        'title': 'PhaseMetrics: Products'
    }
    return render_template('main/products.html', vars=page_vars)


@main.route('/products/hi')
def product_hi():
    """Render product page for PhaseMetrics HI"""
    page_vars = {
        'sidebar_class': ' sidebar',
        'jumbotron': True,
        'sidebar_right': True,
        'title': 'PhaseMetrics HI',
        'page_header': 'PhaseMetrics HI'
    }
    return render_template('main/product_hi.html', vars=page_vars)


@main.route('/products/android')
def product_droid():
    """Render product page for PhaseMetrics Android"""
    page_vars = {
        'jumbotron': True,
        'title': 'PhaseMetrics Android',
        'page_header': 'PhaseMetrics Android'
    }
    return render_template('main/product_droid.html', vars=page_vars)


@main.route('/services')
def services():
    """Render Services page."""
    page_vars = {
        'title': 'Page Not Found',
        'page_header': 'Page Not Found'
    }

    return render_template('error/404.html', vars=page_vars), 404


@main.route('/developers')
@register_breadcrumb(main, 'breadcrumbs.docs', 'Developer Documentation')
def developers():
    """Render Developers page."""
    page_vars = {
        'title': 'PhaseMetrics: Developer Information'
    }
    return render_template('main/developers.html', vars=page_vars)


@main.route('/developers/docs')
@register_breadcrumb(main, 'breadcrumbs.docs.intro', 'Introduction')
def developer_docs():
    """Render developer documentation home page."""
    page_vars = {
        'sidebar_class': ' sidebar',
        'title': 'Developer Documentation',
        'navwell': True,
        'page_header': 'Developer Documentation',
        'sidebar_left': True
    }
    return render_template('main/developer_docs.html', vars=page_vars)


@main.route('/contact', methods=['GET', 'POST'])
def contact():
    """Render Contact page."""
    form = ContactForm()

    if form.validate_on_submit():
        mail_vars = {
            'name': 'Admin',
            'site_name': 'PhaseMetrics.io',
            'from': '{0} ({1})'.format(form.name.data, form.email.data),
            'msg': form.msg.data
        }
        text = render_template('mail/site-contact.txt', vars=mail_vars)
        html = render_template('mail/site-contact.html', vars=mail_vars)

        subject = 'Contact via PhaseMetrics.io'
        cc = form.email.data if form.cc.data else None
        send_mail(subject, recipients=['admin@phasemetrics.io'],
                  cc=[cc], text=text, html=html, reply_to=form.email.data)

        flash('Your message has been sent. ' +
              'Thank you for contacting PhaseMetrics.', 'success')
        return redirect(url_for('main.contact'))

    page_vars = {
        'title': 'PhaseMetrics: Contact Us',
        'page_header': 'Contact Us',
        'form': form
    }
    return render_template('main/contact.html', vars=page_vars)

app/templates/main/contact.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
<p class="col-md-6">Do you need more information? Do you want to discuss a cool idea you have?
    Or, do you just want to say hi? Whatever the case may be, you can use the
    form below to get in touch with the PhaseMetrics team.</p>
<form class="form col-md-6" role="form" method="post">
    {{ vars['form'].hidden_tag() }}
        
    <div class="form-group{% if vars['form'].name.errors %} has-error{% endif %}">
        {{ vars['form'].name.label(class_='control-label') }}
        {{ vars['form'].name(class_='form-control') }}
        {% for message in vars['form'].name.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
        
    <div class="form-group{% if vars['form'].email.errors %} has-error{% endif %}">
        {{ vars['form'].email.label(class_='control-label') }}
        {{ vars['form'].email(class_='form-control') }}
        {% for message in vars['form'].email.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
        
    <div class="form-group{% if vars['form'].msg.errors %} has-error{% endif %}">
        {{ vars['form'].msg.label(class_='control-label') }}
        {{ vars['form'].msg(class_='form-control', rows=5) }}
        {% for message in vars['form'].msg.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    
    <div class="form-group{% if vars['form'].cc.errors %} has-error{% endif %}">
        {{ vars['form'].cc }}
        {{ vars['form'].cc.label(class_='control-label') }}
        {% for message in vars['form'].cc.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    {{ vars['form'].submit(class_='btn btn-default') }}
</form>
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/main/developer_docs.html
{% extends "base.html" %}

{% block jumbotron %}
{{ super() }}
{% endblock %}


{% block sidebar_left %}
<div class="panel panel-default">
    <div class="panel-heading">Documentation</div>
    <div class="panel-body">
        <ul>
            <li><a href="{{ url_for('main.developer_docs') }}">Introduction</a></li>
            <li><a href="#">Agent Systems</a></li>
            <li><a href="#">Deployment with PhaseMetrics</a></li>
        </ul>
    </div>
</div>
{% endblock sidebar_left %}

{% block page_content %}
{{ super() }}
<p>Our products allow developers to quickly deploy the infrastructure required
    to develop distributed agent-based intelligent systems.</p>
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/main/developers.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}

{% block jumbotron %}
{{ super() }}
<div class="jumbo-inner">
    <div class="container">
        <h1>Collective Intelligence</h1>
        <p>A suite of tools for deploying and managing multiagent-based distributed systems.</p>
        <a class="btn btn-default btn-lg calltoaction" href="{{ url_for('auth.register')
                                                if not current_user.is_authenticated()
                                                else url_for('project.index') }}">Get Started</a>
    </div>
</div>
{% endblock %}

{% block page_content %}
{{ super() }}
<div id="pm-feature-container">
    <div class="pm-feature col-md-4">
        <div class="image tolerance"><div class="icon"></div></div>
        <h3>Fault Tolerance</h3>
        <p>Your core infrastructure is fully replicated for maximal uptime.</p>
    </div>
    <div class="pm-feature col-md-4">
        <div class="image connectivity"><div class="icon"></div></div>
        <h3>Connectivity</h3>
        <p>Internet connected and ready to deploy distributed systems large
            and small.</p>
    </div>
    <div class="pm-feature col-md-4">
        <div class="image privacy"><div class="icon"></div></div>
        <h3>Privacy</h3>
        <p>Dedicated platform resources that are only accessible to your applications.</p>
    </div>
</div>
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/main/product_droid.html
{% extends "base.html" %}

{% block jumbotron %}
{{ super() }}
<div class="jumbo-inner">
    <div class="container">
        <h1></h1>
    </div>
</div>
{% endblock %}

{% block page_content %}
{{ super() }}
<p>One Android application to rule them all.</p>
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/main/product_hi.html
{% extends "base.html" %}

{% block jumbotron %}
{{ super() }}
<div class="jumbo-inner">
    <div class="container">
        <h1></h1>
    </div>
</div>
{% endblock %}

{% block page_content %}
{{ super() }}
<p>Our Hosted Intelligence platform is the go-to solution for deploying distributed
    agent-based intelligent systems.</p>
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/main/products.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}

app/templates/main/services.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
{% endblock %}

{% block styles%}
{{ super() }}
{% endblock %}

{% block scripts%}
{{ super() }}
{% endblock %}