app/config/forms.py
"""Implements forms used in the configuration ui."""

from flask_wtf import Form

from wtforms import (
    BooleanField,
    StringField,
    SubmitField,
    ValidationError,
)
from wtforms.fields.html5 import EmailField
from wtforms.validators import (
    Email,
    Length,
    Required,
)

from app.utils.models import (
    User,
)


class FlagsForm(Form):
    submit = SubmitField('Save Changes')


class AddFlagForm(Form):
    name = StringField('Name', validators=[Length(max=32)])
    description = StringField(
        'Description', validators=[Length(max=64)])
    value = BooleanField('value')
    submit = SubmitField('Create Flag')


class EditFlagForm(Form):
    name = StringField('Name', validators=[Length(max=32)])
    description = StringField(
        'Description', validators=[Length(max=64)])
    value = BooleanField('value')
    submit = SubmitField('Save Changes')


class InviteUserForm(Form):
    name = StringField('Name', validators=[Required()])
    email = EmailField('Email address', validators=[Required(), Email()])
    submit = SubmitField('Send Invitation')

    @staticmethod
    def validate_email(dummy_form, field):
        """Check that the supplied email does not exist in the system."""
        user = User.query.filter_by(email=field.data).first()
        if user is not None:
            raise ValidationError('There is already an account associated \
                                  with the supplied email address.')

app/config/__init__.py
"""Implements the configuration ui."""

from flask import Blueprint

config = Blueprint('config', __name__)

from . import (
    forms,
    views,
)

__all__ = ['config']

app/config/views.py
"""Implements configuration endpoints."""

from datetime import datetime

from flask import (
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_breadcrumbs import register_breadcrumb
from flask_login import (
    current_user,
    login_required,
)

from wtforms import BooleanField

from app import db
from app.config import config
from app.config.forms import (
    AddFlagForm,
    EditFlagForm,
    FlagsForm,
    InviteUserForm,
)
from app.confirm import confirm_required
from app.utils.constructors import edit_flag
from app.utils.decorators import (
    confirmed_required,
    admin_required,
)
from app.utils.mail import send_mail
from app.utils.models import (
    Flag,
    User,
    UserInvitation,
)


@config.route('/')
@login_required
@confirmed_required
@admin_required
@register_breadcrumb(config, 'breadcrumbs.config', 'Configuration')
def index():
    page_vars = {
        'sidebar_class': ' two-column',
        'sidebar_right': True,
        'navwell': True,
        'title': 'Site Configuration',
        'page_header': 'Site Configuration'
    }
    return render_template('config/index.html', vars=page_vars)


@config.route('/flags', methods=['GET', 'POST'])
@login_required
@confirmed_required
@admin_required
@register_breadcrumb(config, 'breadcrumbs.config.flags', 'System Flags')
def flags():
    flags = Flag.query.all()
    flag_ids = {}

    for flag in flags:
        setattr(FlagsForm, flag.name, BooleanField(flag.name))
        flag_ids[flag.name] = flag.id

    form = FlagsForm()

    if form.validate_on_submit():
        for flag in flags:
            flag.value = form[flag.name].data
            flag.last_modified = datetime.now()
            db.session.add(flag)

        db.session.commit()

        flash('Changes saved.', 'success')

    for flag in flags:
        form[flag.name].data = flag.value
        form[flag.name].description = flag.description

    page_vars = {
        'navwell': True,
        'title': 'System Flags',
        'page_header': 'Configure System Flags',
        'form': form,
        'flag_ids': flag_ids
    }
    return render_template('config/flags.html', vars=page_vars)


@config.route('/flags/add', methods=['GET', 'POST'])
@login_required
@confirmed_required
@admin_required
@register_breadcrumb(config, 'breadcrumbs.config.flags.add', 'New Flag')
def add_flag():
    form = AddFlagForm()

    if form.validate_on_submit():
        flag = Flag(
            name=form.name.data,
            description=form.description.data,
            value=form.value.data,
            last_modified=datetime.now()
        )

        db.session.add(flag)
        db.session.commit()

        flash('New flag `{0}` created.'.format(flag.name), 'success')
        return redirect(url_for('config.flags'))

    page_vars = {
        'navwell': True,
        'title': 'New Flag',
        'page_header': 'Create a New Flag',
        'form': form
    }
    return render_template('config/addflag.html', vars=page_vars)


@config.route('/flags/<int:fid>/edit', methods=['GET', 'POST'])
@login_required
@confirmed_required
@admin_required
@register_breadcrumb(config, 'breadcrumbs.config.flags.edit', '', dynamic_list_constructor=edit_flag)
def edit_flag(fid):
    flag = Flag.query.filter_by(id=fid).first()
    form = EditFlagForm()

    if form.validate_on_submit():
        flag.name = form.name.data
        flag.description = form.description.data
        flag.value = form.value.data
        flag.last_modified = datetime.now()

        db.session.add(flag)
        db.session.commit()

        flash('Flag `{0}` updated.'.format(flag.name), 'success')
        return redirect(url_for('config.flags'))

    form.name.data = flag.name
    form.description.data = flag.description
    form.value.data = flag.value

    page_vars = {
        'navwell': True,
        'title': 'Edit Flag',
        'page_header': 'Edit ' + flag.name,
        'form': form,
        'flag': flag
    }
    return render_template('config/editflag.html', vars=page_vars)


@config.route('/flags/<int:fid>/delete', methods=['GET', 'POST'])
@login_required
@confirmed_required
@admin_required
@confirm_required(
    'Are you sure you want to delete this flag?',
    'I am sure', 'config.edit_flag', ['fid'], 'danger'
)
def delete_flag(fid):
    flag = Flag.query.filter_by(id=fid).first()
    delattr(FlagsForm, flag.name)
    db.session.delete(flag)
    flash('Flag `{0}` has been deleted.'.format(flag.name), 'success')
    return redirect(url_for('config.flags'))


@config.route('/users', methods=['GET', 'POST'])
@login_required
@confirmed_required
@admin_required
@register_breadcrumb(config, 'breadcrumbs.config.users', 'Manage Users')
def users():
    users = User.query.all()

    page_vars = {
        'title': 'Manage Users',
        'navwell': True,
        'page_header': 'Manage Users',
        'users': users
    }
    return render_template('config/users.html', vars=page_vars)


@config.route('/users/invite', methods=['GET', 'POST'])
@login_required
@confirmed_required
@admin_required
@register_breadcrumb(config, 'breadcrumbs.config.users.invite', 'Invite User')
def invite_user():
    form = InviteUserForm()

    if form.validate_on_submit():
        inv = UserInvitation(
            name=form.name.data,
            email=form.email.data,
            token=UserInvitation.generate_invitation_token(),
            sent_by=current_user.id
        )
        reg_url = url_for('auth.register', token=inv.token, _external=True)

        mail_vars = {
            'name': inv.name,
            'site_name': 'PhaseMetrics',
            'registration_token': inv.token,
            'registration_url': reg_url
        }
        text = render_template('mail/user-invitation.txt', vars=mail_vars)
        html = render_template('mail/user-invitation.html', vars=mail_vars)

        subject = 'Your Invitation to Register at PhaseMetrics'
        send_mail(subject, recipients=[inv.email], text=text, html=html)
        inv.sent_on = datetime.now()
        db.session.add(inv)
        db.session.commit()

        flash('An invitation to register has been sent to {0}.'
              .format(inv.email), 'success')
        return redirect(url_for('config.users'))

    page_vars = {
        'title': 'Invite User',
        'navwell': True,
        'page_header': 'Invite User',
        'form': form
    }
    return render_template('config/inviteuser.html', vars=page_vars)

app/templates/config/addflag.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
<form id="add-flag-form" method="post" class="form" role="form">
    {{ vars['form'].hidden_tag() }}
    <div class="form-group{% if vars['form'].name.errors %} has-error{% endif %}">
        {{ vars['form'].name.label(class_='control-label') }}
        {{ vars['form'].name(class_='form-control', maxlength=32) }}
        {% for message in vars['form'].name.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    <div class="form-group{% if vars['form'].description.errors %} has-error{% endif %}">
        {{ vars['form'].description.label(class_='control-label') }}
        {{ vars['form'].description(class_='form-control', maxlength=64) }}
        {% for message in vars['form'].description.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    <div class="form-group{% if vars['form'].value.errors %} has-error{% endif %}">
        {{ vars['form'].value }}
        {{ vars['form'].value.label(class_='control-label') }}
        {% for message in vars['form'].value.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    
    <a role="button" class="btn btn-default"
        href="{{ url_for('config.flags')}}">
        Cancel
    </a>
    {{ vars['form'].submit(class_='btn btn-default') }}
</form>
{% endblock page_content %}

{% block styles%}
{{ super() }}
{% endblock styles %}

{% block scripts%}
{{ super() }}
{% endblock scripts %}

app/templates/config/editflag.html
{% extends "base.html" %}

{% block page_actions %}
{{ super() }}
<a role="button" class="btn btn-danger"
    href="{{ url_for('config.delete_flag', fid=vars['flag'].id) }}">
    Delete
</a>
{% endblock %}

{% block page_content %}
{{ super() }}
<form id="edit-flag-form" method="post" class="form" role="form">
    {{ vars['form'].hidden_tag() }}
    <div class="form-group{% if vars['form'].name.errors %} has-error{% endif %}">
        {{ vars['form'].name.label(class_='control-label') }}
        {{ vars['form'].name(class_='form-control', maxlength=32) }}
        {% for message in vars['form'].name.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    <div class="form-group{% if vars['form'].description.errors %} has-error{% endif %}">
        {{ vars['form'].description.label(class_='control-label') }}
        {{ vars['form'].description(class_='form-control', maxlength=64) }}
        {% for message in vars['form'].description.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    <div class="form-group{% if vars['form'].value.errors %} has-error{% endif %}">
        {{ vars['form'].value }}
        {{ vars['form'].value.label(class_='control-label') }}
        {% for message in vars['form'].value.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    
    <a role="button" class="btn btn-default"
        href="{{ url_for('config.flags')}}">
        Cancel
    </a>
    {{ vars['form'].submit(class_='btn btn-default') }}
</form>
{% endblock page_content %}

{% block styles%}
{{ super() }}
{% endblock styles %}

{% block scripts%}
{{ super() }}
{% endblock scripts %}

app/templates/config/flags.html
{% extends "base.html" %}

{% block page_actions %}
{{ super() }}
<a role="button" class="btn btn-default"
    href="{{ url_for('config.add_flag')}}">
    Create Flag
</a>
{% endblock %}

{% block page_content %}
{{ super() }}
<form id="system-flags-form" method="post" class="form" role="form">
    {{ vars['form'].hidden_tag() }}
    {% for field in vars['form'] %}
        {% if field.name not in ['csrf_token', 'submit'] %}
            <div class="form-group{% if vars['form'][field.name].errors %} has-error{% endif %}">
                {{ vars['form'][field.name] }}
                {{ vars['form'][field.name].label(class_='control-label') }}
                (<a href="{{ url_for('config.edit_flag', fid=vars['flag_ids'][field.name]) }}")>edit</a>)<br />
                {{ vars['form'][field.name].description }}
                {% for message in vars['form'][field.name].errors %}
                <p class="help-block">{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
    {% endfor %}
    
    <a role="button" class="btn btn-default"
        href="{{ url_for('config.index')}}">
        Cancel
    </a>
    {{ vars['form'].submit(class_='btn btn-default') }}
</form>
{% endblock page_content %}

{% block styles%}
{{ super() }}
{% endblock styles %}

{% block scripts%}
{{ super() }}
{% endblock scripts %}

app/templates/config/index.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
<div class="panel panel-default">
    <div class="panel-heading">System</div>
    <div class="panel-body">
        <dl>
            <dt><a href="{{ url_for('config.flags') }}">Flags</a></dt>
            <dd>Configure system flags.</dd>
        </dl>
    </div>
</div>
{% endblock page_content %}

{% block sidebar_right %}
<div class="panel panel-default">
    <div class="panel-heading">People</div>
    <div class="panel-body">
        <dl>
            <dt><a href="{{ url_for('config.users') }}">Users</a></dt>
            <dd>Manage users.</dd>
            <dt><a href="#">Roles</a></dt>
            <dd>Manage user roles.</dd>
        </dl>
    </div>
</div>
{% endblock sidebar_right %}

{% block styles%}
{{ super() }}
{% endblock styles %}

{% block scripts%}
{{ super() }}
{% endblock scripts %}

app/templates/config/inviteuser.html
{% extends "base.html" %}

{% block page_content %}
{{ super() }}
<p>Enter the email address of the person you wish to invite.</p>
<form id="invite-user-form" method="post" class="form" role="form">
    {{ vars['form'].hidden_tag() }}
    <div class="form-group{% if vars['form'].name.errors %} has-error{% endif %}">
        {{ vars['form'].name.label(class_='control-label') }}
        {{ vars['form'].name(class_='form-control', maxlength=32) }}
        {% for message in vars['form'].name.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    <div class="form-group{% if vars['form'].email.errors %} has-error{% endif %}">
        {{ vars['form'].email.label(class_='control-label') }}
        {{ vars['form'].email(class_='form-control', maxlength=32) }}
        {% for message in vars['form'].email.errors %}
        <p class="help-block">{{ message }}</p>
        {% endfor %}
    </div>
    
    <a role="button" class="btn btn-default"
        href="{{ url_for('config.users')}}">
        Cancel
    </a>
    {{ vars['form'].submit(class_='btn btn-default') }}
</form>
{% endblock page_content %}

{% block styles%}
{{ super() }}
{% endblock styles %}

{% block scripts%}
{{ super() }}
{% endblock scripts %}

app/templates/config/users.html
{% extends "base.html" %}

{% block page_actions %}
{{ super() }}
<a class="btn btn-default" href="{{ url_for('config.invite_user') }}">
    Invite User
</a>
{% endblock %}

{% block page_content %}
{{ super() }}
<table class="table table-condensed">
    <thead>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
            <th>Registered on</th>
            <th>Confirmed</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for user in vars['users'] %}
            <tr>
                <th scope="row">{{ user.id }}</th>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.registered_on }}</td>
                <td>{{ 'Yes' if user.confirmed else 'No' }}</td>
                <td>{{ 'Active' if user.active else 'Blocked' }}</td>
                <td>
                    <a href="#">edit</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock page_content %}

{% block styles%}
{{ super() }}
{% endblock styles %}

{% block scripts%}
{{ super() }}
{% endblock scripts %}